name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable artifact file
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}
      - name: list file
        run: ls 
      - name: Output information
        run: echo "Deploying & uploading..."